from .university_image import UniversityImage  # noqa
from .detail import Detail  # noqa
from .university_detail import UniversityDetail  # noqa
from .lesson_group_speciality import LessonGroupSpeciality  # noqa
from .year import Year  # noqa
from .grant_count import GrantCount  # noqa
from .grant_university_count import GrantUniversityCount  # noqa
from .detail_speciality import DetailSpeciality  # noqa
from .speciality_detail_info import SpecialityDetailInfo  # noqa
