# Generated by Django 3.2.12 on 2022-07-19 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test_type', to='accounts.usertesttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts"."user_test_type',
            },
        ),
    ]
