# Generated by Django 3.2.12 on 2022-07-10 09:30

import base.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[base.service.validate_size_image, base.service.validate_mb_image]),
        ),
    ]
