# Generated by Django 3.2.12 on 2022-07-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20220719_2252'),
        ('accounts', '0002_usertesttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertesttype',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test_type', to='quizzes.testtype'),
        ),
    ]
