# Generated by Django 3.2.9 on 2022-10-24 12:26

import django.db.models.deletion
from django.db import migrations, models

import base.constant


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_alter_testtypelesson_language'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('kz', 'KAZAKH'), ('ru', 'RUSSIAN')], db_index=True, default=base.constant.TestLang['KAZAKH'], max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='test_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.testtype'),
        ),
    ]
