# Generated by Django 3.2.12 on 2023-03-03 08:05

import base.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230303_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[base.service.validate_size_image, base.service.validate_mb_image]),
        ),
    ]
