# Generated by Django 3.2.12 on 2023-03-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
