# Generated by Django 3.2.12 on 2023-03-30 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0034_auto_20230331_0223'),
        ('accounts', '0006_alter_city_name_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='quizzes.country'),
        ),
    ]
