# Generated by Django 3.2.12 on 2022-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
