# Generated by Django 3.2.12 on 2022-07-19 16:52

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_testtype_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lesson',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='questionlevel',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tagquestion',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='testtype',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='variant',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='variantquestion',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
