# Generated by Django 3.2.12 on 2023-01-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20221217_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='lesson'),
        ),
    ]
