# Generated by Django 3.2.12 on 2022-10-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20221008_1625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonquestionlevel',
            unique_together={('test_type_lesson', 'question_level')},
        ),
    ]
