# Generated by Django 3.2.12 on 2022-07-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20220719_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelManagers(
            name='lesson',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='questionlevel',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tagquestion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='testtype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='variant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='variantquestion',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='TestTypeLessonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lesson_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_type_lesson_groups', to='quizzes.lessongroup')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_type_lesson_groups', to='quizzes.testtype')),
            ],
            options={
                'db_table': 'quiz"."test_type_lesson_group',
            },
        ),
        migrations.CreateModel(
            name='TestTypeLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('main', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_type_lessons', to='quizzes.lesson')),
                ('test_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_type_lessons', to='quizzes.testtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
