# Generated by Django 3.2.12 on 2023-01-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_lesson_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='test_type'),
        ),
        migrations.AlterField(
            model_name='variantgroup',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
