# Generated by Django 3.2.12 on 2023-02-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20230122_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='passanswer',
            name='user_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_answers', to='quizzes.uservariant'),
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='quizzes_type',
            field=models.CharField(choices=[('BY_LESSON', 'BY_LESSON'), ('FULL_TEST_ENT', 'FULL_TEST_ENT')], db_index=True, max_length=128, null=True),
        ),
    ]
