# Generated by Django 3.2.12 on 2022-10-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20221008_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_questions', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='tagquestion',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_questions', to='quizzes.tag'),
        ),
    ]
