# Generated by Django 3.2.12 on 2023-02-04 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0005_auto_20230204_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFullScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('unattem', models.IntegerField(default=0)),
                ('user_score', models.IntegerField(default=0)),
                ('number_of_question', models.IntegerField(default=0)),
                ('number_of_score', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_full_score', to=settings.AUTH_USER_MODEL)),
                ('user_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_full_score', to='quizzes.uservariant')),
            ],
            options={
                'db_table': 'quiz"."test_full_score',
            },
        ),
    ]
