# Generated by Django 3.1 on 2022-08-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20220805_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.testtypelesson'),
        ),
    ]
