# Generated by Django 3.2.9 on 2022-10-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='math',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='math',
            field=models.BooleanField(default=False),
        ),
    ]
