# Generated by Django 3.2.12 on 2023-02-04 09:40

import base.constant
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_testfullscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfullscore',
            name='test_type_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_full_score', to='quizzes.testtypelesson'),
        ),
        migrations.AlterField(
            model_name='quizevent',
            name='status',
            field=models.CharField(choices=[('NOT_PASSED', 'NOT_PASSED'), ('CONTINUE', 'CONTINUE'), ('PASSED', 'PASSED')], default=base.constant.Status['NOT_PASSED'], max_length=128),
        ),
        migrations.AlterField(
            model_name='uservariant',
            name='status',
            field=models.CharField(choices=[('NOT_PASSED', 'NOT_PASSED'), ('CONTINUE', 'CONTINUE'), ('PASSED', 'PASSED')], db_index=True, default=base.constant.Status['NOT_PASSED'], max_length=128),
        ),
    ]
