# Generated by Django 3.1 on 2022-08-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20220827_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='lesson',
            new_name='test_type_lesson',
        ),
    ]
