# Generated by Django 3.2.12 on 2023-02-05 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0007_auto_20230204_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('error_name', models.TextField()),
            ],
            options={
                'db_table': 'info"."grade_error',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('grade_ball', models.IntegerField(choices=[(1, 'VERY_BAD'), (2, 'BAD'), (3, 'AVERAGE'), (4, 'GOOD'), (5, 'EXCELLENT')])),
                ('comment', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'info"."grade',
            },
        ),
    ]
