# Generated by Django 3.2.12 on 2023-02-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_grade_gradeerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_error',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='quizzes.gradeerror'),
        ),
    ]
