# Generated by Django 3.2.9 on 2022-10-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20221024_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variant_groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quizzes.variantgroup'),
        ),
    ]
