# Generated by Django 3.2.12 on 2023-02-05 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0009_grade_grade_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='quizzes.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
                ('user_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='quizzes.uservariant')),
            ],
            options={
                'db_table': 'quiz"."mark',
                'ordering': ['-modified'],
                'unique_together': {('question', 'user', 'user_variant')},
            },
        ),
    ]
