# Generated by Django 3.2.9 on 2022-10-24 10:15

import base.constant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_testtype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtypelesson',
            name='lang',
            field=models.IntegerField(choices=[(0, 'KAZAKH'), (1, 'RUSSIAN')], default=base.constant.TestLang['KAZAKH']),
        ),
    ]
