# Generated by Django 3.2.12 on 2023-02-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_auto_20230205_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='is_mark',
            field=models.BooleanField(default=True),
        ),
    ]
