# Generated by Django 3.2.9 on 2022-10-24 10:57

import base.constant
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0011_testtypelesson_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtypelesson',
            name='lang',
        ),
        migrations.AddField(
            model_name='testtypelesson',
            name='language',
            field=models.CharField(choices=[('kz', 'KAZAKH'), ('ru', 'RUSSIAN')], default=base.constant.TestLang['KAZAKH'], max_length=64),
        ),
        migrations.AlterField(
            model_name='uservariant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_variant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_variant', to='quizzes.variant'),
        ),
    ]
