# Generated by Django 3.2.12 on 2023-02-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_mark_is_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoerror',
            name='grade_type',
            field=models.IntegerField(choices=[(1, 'VERY_BAD'), (2, 'BAD'), (3, 'AVERAGE'), (4, 'GOOD'), (5, 'EXCELLENT')], null=True),
        ),
    ]
