# Generated by Django 3.2.9 on 2022-10-24 11:07

import base.constant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_auto_20221024_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtypelesson',
            name='language',
            field=models.CharField(choices=[('kz', 'KAZAKH'), ('ru', 'RUSSIAN')], db_index=True, default=base.constant.TestLang['KAZAKH'], max_length=64),
        ),
    ]
