# Generated by Django 3.2.9 on 2022-10-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_passanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='passanswer',
            name='quizzes_type',
            field=models.CharField(choices=[('BY_LESSON', 'BY_LESSON')], db_index=True, max_length=128, null=True),
        ),
    ]
