# Generated by Django 3.2.12 on 2023-02-16 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0014_questionquizeventscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionquizeventscore',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_event_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
