# Generated by Django 3.2.9 on 2022-10-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_passanswer_quizzes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('quizzes_type', models.CharField(choices=[('BY_LESSON', 'BY_LESSON')], db_index=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'quiz"."quiz_event',
            },
        ),
        migrations.CreateModel(
            name='QuizEventQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_event_questions', to='quizzes.question')),
                ('quiz_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_event_questions', to='quizzes.quizevent')),
            ],
            options={
                'db_table': 'quiz"."quiz_event_question',
            },
        ),
    ]
