# Generated by Django 3.2.12 on 2023-02-19 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_questionquizeventscore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='user_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='quizzes.uservariant'),
        ),
    ]
