# Generated by Django 3.2.9 on 2022-10-24 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0016_quizevent_quizeventquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizeventquestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_event_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
