# Generated by Django 3.2.9 on 2022-10-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_quizeventquestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passanswer',
            name='quizzes_type',
        ),
        migrations.AddField(
            model_name='passanswer',
            name='quiz_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_answers', to='quizzes.quizevent'),
        ),
    ]
