# Generated by Django 3.2.12 on 2023-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_grade_quiz_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chosen_icon',
            field=models.FileField(blank=True, null=True, upload_to='lesson'),
        ),
    ]
