# Generated by Django 3.2.9 on 2022-10-25 08:32

import base.constant
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_auto_20221024_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizevent',
            name='status',
            field=models.CharField(choices=[('NOT_PASSED', 'NOT_PASSED')], default=base.constant.Status['NOT_PASSED'], max_length=128),
        ),
        migrations.AddField(
            model_name='quizevent',
            name='test_type_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_event', to='quizzes.testtypelesson'),
        ),
    ]
