# Generated by Django 3.2.12 on 2023-03-04 08:44

import base.constant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_lesson_chosen_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite_type',
            field=models.CharField(choices=[('TEST', 'TEST'), ('SEARCH', 'SEARCH'), ('FLASH_CARD', 'FLASH_CARD')], default=base.constant.FavoriteType['TEST'], max_length=15),
        ),
    ]
