# Generated by Django 3.2.9 on 2022-11-13 11:00

import django.db.models.deletion
from django.db import migrations, models

import base.constant


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_auto_20221025_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpair',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_pairs', to='quizzes.testtypelesson'),
        ),
        migrations.AlterField(
            model_name='questionlevel',
            name='choice',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CHOICE')], default=base.constant.ChoiceType['CHOICE']),
        ),
    ]
