# Generated by Django 3.2.12 on 2023-03-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_alter_favorite_favorite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='test_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservariant',
            name='test_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
