# Generated by Django 3.2.9 on 2022-11-23 16:53

from django.db import migrations, models

import base.constant


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_auto_20221113_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='status',
            field=models.CharField(choices=[('NOT_PASSED', 'NOT_PASSED')], default=base.constant.Status['NOT_PASSED'], max_length=128),
        ),
        migrations.AddField(
            model_name='variant',
            name='sum_question',
            field=models.IntegerField(default=0),
        ),
    ]
