# Generated by Django 3.2.12 on 2022-11-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_auto_20221123_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='variant_groups',
            new_name='variant_group',
        ),
    ]
