# Generated by Django 3.2.12 on 2023-03-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
    ]
