# Generated by Django 3.2.12 on 2022-11-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_rename_variant_groups_variant_variant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantgroup',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_groups', to='quizzes.testtype'),
        ),
    ]
