# Generated by Django 3.2.12 on 2022-11-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_variantgroup_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantgroup',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
