# Generated by Django 3.2.12 on 2023-03-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0024_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='math',
            field=models.BooleanField(default=False),
        ),
    ]
