# Generated by Django 3.2.12 on 2022-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0024_variantgroup_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantgroup',
            name='hours',
        ),
        migrations.AddField(
            model_name='variantgroup',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
