# Generated by Django 3.2.12 on 2022-11-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_auto_20221126_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantgroup',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
