# Generated by Django 3.2.12 on 2023-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0026_topic_topicquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
