# Generated by Django 3.2.12 on 2023-03-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0028_auto_20230318_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantLessonCommonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('common_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_lesson_common_questions', to='quizzes.commonquestion')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_lesson_common_questions', to='quizzes.testtypelesson')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_lesson_common_questions', to='quizzes.variant')),
            ],
            options={
                'db_table': 'quiz"."variant_lesson_common_question',
            },
        ),
    ]
