# Generated by Django 3.2.12 on 2022-11-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0028_alter_lessongroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
