# Generated by Django 3.2.12 on 2022-11-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0029_alter_lessongroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='lesson_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_variants', to='quizzes.lessongroup'),
        ),
    ]
