# Generated by Django 3.2.12 on 2022-12-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0030_uservariant_lesson_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_code', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'quiz"."answer_sign',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.answersign'),
        ),
    ]
