# Generated by Django 3.2.12 on 2023-03-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0030_topic_topicquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='test_type_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.testtypelesson'),
        ),
    ]
