# Generated by Django 3.2.12 on 2022-12-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0031_auto_20221206_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersign',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
