# Generated by Django 3.2.12 on 2023-03-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0031_alter_topic_test_type_lesson'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantquestion',
            unique_together={('variant', 'question')},
        ),
    ]
