# Generated by Django 3.2.12 on 2022-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0032_answersign_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlevel',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
