# Generated by Django 3.2.12 on 2022-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0033_questionlevel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlevel',
            name='name_code',
            field=models.CharField(db_index=True, default=123, max_length=255),
            preserve_default=False,
        ),
    ]
