# Generated by Django 3.2.12 on 2023-03-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0034_auto_20230331_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='country',
        ),
    ]
