# Generated by Django 3.2.12 on 2023-03-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0035_remove_university_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='address',
        ),
    ]
