# Generated by Django 3.2.12 on 2023-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0037_auto_20230331_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='description',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='address',
        ),
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
        migrations.RemoveField(
            model_name='university',
            name='short_name',
        ),
        migrations.AddField(
            model_name='speciality',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='short_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='short_name_kz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='short_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='address_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='comforts',
            field=models.ManyToManyField(through='quizzes.ComfortUniversity', to='quizzes.Comfort'),
        ),
        migrations.AddField(
            model_name='university',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='short_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='short_name_kz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='short_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
