# Generated by Django 3.2.12 on 2023-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0038_auto_20230401_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='generation',
            field=models.BooleanField(default=False),
        ),
    ]
