# Generated by Django 3.2.12 on 2023-04-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0040_university_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='details',
        ),
        migrations.AddField(
            model_name='university',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
