# Generated by Django 3.2.12 on 2023-04-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0041_auto_20230410_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
