# Generated by Django 3.2.12 on 2023-04-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0042_alter_university_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='university',
            name='address_kz',
        ),
        migrations.RemoveField(
            model_name='university',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='university',
            name='code',
        ),
        migrations.RemoveField(
            model_name='university',
            name='status',
        ),
    ]
