# Generated by Django 3.2.12 on 2023-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0043_auto_20230415_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='avg_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speciality',
            name='avg_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speciality',
            name='min_bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speciality',
            name='min_bal_with_quota',
            field=models.IntegerField(default=0),
        ),
    ]
