# Generated by Django 3.2.12 on 2023-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0044_auto_20230416_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityspeciality',
            name='avg_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityspeciality',
            name='min_bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityspeciality',
            name='min_bal_with_quota',
            field=models.IntegerField(default=0),
        ),
    ]
