# Generated by Django 3.2.12 on 2023-04-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0039_variant_generation'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_kz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('icon', models.FileField(upload_to='university_detail')),
                ('is_filter', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'quiz"."detail',
            },
        ),
        migrations.CreateModel(
            name='UniversityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=128)),
                ('dimension', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_details', to='universities.detail')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_details', to='quizzes.university')),
            ],
            options={
                'db_table': 'quiz"."university_detail',
            },
        ),
    ]
