# Generated by Django 3.2.12 on 2023-04-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0042_alter_university_video_link'),
        ('universities', '0002_detail_universitydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonGroupSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=128)),
                ('dimension', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('lesson_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_groups_specialities', to='quizzes.lessongroup')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_groups_specialities', to='quizzes.speciality')),
            ],
            options={
                'db_table': 'quiz"."lesson_group_speciality',
            },
        ),
    ]
