# Generated by Django 3.2.12 on 2023-04-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_lessongroupspeciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessongroupspeciality',
            old_name='university',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='lessongroupspeciality',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='lessongroupspeciality',
            name='value',
        ),
    ]
