# Generated by Django 3.2.12 on 2023-04-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20230415_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydetail',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
