# Generated by Django 3.2.12 on 2023-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_universitydetail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitydetail',
            old_name='dimension',
            new_name='value_en',
        ),
        migrations.AddField(
            model_name='universitydetail',
            name='value_ru',
            field=models.CharField(default='', max_length=128),
        ),
    ]
