# Generated by Django 3.2.12 on 2023-04-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20230415_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitydetail',
            old_name='value',
            new_name='value_kz',
        ),
    ]
