# Generated by Django 3.2.12 on 2023-04-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0045_auto_20230416_0051'),
        ('universities', '0007_rename_value_universitydetail_value_kz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'universities"."year',
            },
        ),
        migrations.CreateModel(
            name='GrantCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_counts', to='quizzes.speciality')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_counts', to='universities.year')),
            ],
            options={
                'db_table': 'universities"."grant_count',
            },
        ),
    ]
